### ISSUE TITLE
Upload to WS1 does not work - 400 (Bad Request)

### ISSUE THREAD

**Issue by msconfig87** [tbwfdu/fetch#16]
2025-05-19 11:16:19.138 +02:00 [ERR] [AppUpdatesPage] App Add Failed: Adobe Acrobat Reader DC
2025-05-19 11:16:31.684 +02:00 [INF] Getting All Windows Native Apps from UEM
2025-05-19 11:16:38.520 +02:00 [INF] Native Windows Apps Found: 210
2025-05-19 11:18:09.748 +02:00 [INF] [AppUpdatesPage] Added Miro to Queue
2025-05-19 11:18:16.544 +02:00 [INF] [AppUpdatesPage] User confirmation requested
2025-05-19 11:18:17.859 +02:00 [INF] [AppUpdatesPage] User confirmation confirmed
2025-05-19 11:18:17.859 +02:00 [INF] [AppUpdatesPage] Apps in Queue: 1
2025-05-19 11:18:18.373 +02:00 [INF] [AppUpdatesPage] Initiating Processing of Queue
2025-05-19 11:18:18.373 +02:00 [INF] [AppUpdatesPage] ModeRequested: uploadToUem]
2025-05-19 11:18:18.485 +02:00 [INF] [AppUpdatesPage] Downloads to Process: 1
2025-05-19 11:18:18.486 +02:00 [INF] [AppUpdatesPage] Downloading Miro
2025-05-19 11:18:18.488 +02:00 [INF] [DownloadService] Creating Path: C:\Users\mjo\AppData\Local\Fetch\Downloads\Miro.Miro\0.11.99\x64\exe
2025-05-19 11:18:18.488 +02:00 [INF] [DownloadService] Download Started: https://desktop.miro.com/platforms/win32-nsis-pu/Miro-setup.exe
2025-05-19 11:18:21.183 +02:00 [INF] [DownloadService] Download OK: https://desktop.miro.com/platforms/win32-nsis-pu/Miro-setup.exe
2025-05-19 11:18:21.183 +02:00 [INF] [DownloadService] Download OK: https://desktop.miro.com/platforms/win32-nsis-pu/Miro-setup.exe
2025-05-19 11:18:21.688 +02:00 [INF] [DownloadService] Installer downloaded successfully: Miro
2025-05-19 11:18:21.689 +02:00 [INF] [AppUpdatesPage] Installer downloaded successfully: Miro
2025-05-19 11:18:22.701 +02:00 [INF] [AppUpdatesPage] Starting Installer Upload
2025-05-19 11:18:22.701 +02:00 [INF] [AppUpdatesPage] Uploading Custom Install/Uninstall Scripts
2025-05-19 11:18:22.823 +02:00 [ERR] Response status code does not indicate success: 400 (Bad Request).
2025-05-19 11:18:22.823 +02:00 [ERR] System.Net.Http
2025-05-19 11:18:22.890 +02:00 [ERR] Response status code does not indicate success: 400 (Bad Request).
2025-05-19 11:18:22.890 +02:00 [ERR] System.Net.Http
2025-05-19 11:18:42.021 +02:00 [INF] [DownloadService] Upload Complete.
2025-05-19 11:18:42.530 +02:00 [INF] [DownloadService] Creating Application in App Catalog
2025-05-19 11:18:42.625 +02:00 [INF] [DownloadService] Upload Success: False
2025-05-19 11:18:42.628 +02:00 [ERR] [AppUpdatesPage] App Add Failed: Miro
2025-05-19 11:21:08.379 +02:00 [INF] [AppUpdatesPage] Added Omnissa Horizon Client to Queue
2025-05-19 11:21:15.592 +02:00 [INF] [AppUpdatesPage] User confirmation requested
2025-05-19 11:21:16.676 +02:00 [INF] [AppUpdatesPage] User confirmation confirmed
2025-05-19 11:21:16.676 +02:00 [INF] [AppUpdatesPage] Apps in Queue: 1
2025-05-19 11:21:17.183 +02:00 [INF] [AppUpdatesPage] Initiating Processing of Queue
2025-05-19 11:21:17.183 +02:00 [INF] [AppUpdatesPage] ModeRequested: uploadToUem]
2025-05-19 11:21:17.295 +02:00 [INF] [AppUpdatesPage] Downloads to Process: 1
2025-05-19 11:21:17.296 +02:00 [INF] [AppUpdatesPage] Downloading Omnissa Horizon Client
2025-05-19 11:21:17.297 +02:00 [INF] [DownloadService] Creating Path: C:\Users\mjo\AppData\Local\Fetch\Downloads\Omnissa.HorizonClient\8.15.0.24358\x64\exe
2025-05-19 11:21:17.297 +02:00 [INF] [DownloadService] Download Started: https://download3.omnissa.com/software/CART26FQ1_WIN_2503/Omnissa-Horizon-Client-2503-8.15.0-14236595709.exe
2025-05-19 11:21:25.474 +02:00 [INF] [DownloadService] Download OK: https://download3.omnissa.com/software/CART26FQ1_WIN_2503/Omnissa-Horizon-Client-2503-8.15.0-14236595709.exe
2025-05-19 11:21:25.494 +02:00 [INF] [DownloadService] Download OK: https://download3.omnissa.com/software/CART26FQ1_WIN_2503/Omnissa-Horizon-Client-2503-8.15.0-14236595709.exe
2025-05-19 11:21:25.994 +02:00 [INF] [DownloadService] Installer downloaded successfully: Omnissa Horizon Client
2025-05-19 11:21:25.995 +02:00 [INF] [AppUpdatesPage] Installer downloaded successfully: Omnissa Horizon Client
2025-05-19 11:21:27.008 +02:00 [INF] [AppUpdatesPage] Starting Installer Upload
2025-05-19 11:21:27.008 +02:00 [INF] [AppUpdatesPage] Uploading Custom Install/Uninstall Scripts
2025-05-19 11:21:27.153 +02:00 [ERR] Response status code does not indicate success: 400 (Bad Request).
2025-05-19 11:21:27.153 +02:00 [ERR] System.Net.Http
2025-05-19 11:21:27.278 +02:00 [ERR] Response status code does not indicate success: 400 (Bad Request).
2025-05-19 11:21:27.278 +02:00 [ERR] System.Net.Http
2025-05-19 11:22:52.197 +02:00 [INF] [DownloadService] Upload Complete.
2025-05-19 11:22:52.714 +02:00 [INF] [DownloadService] Creating Application in App Catalog
2025-05-19 11:22:52.797 +02:00 [INF] [DownloadService] Upload Success: False
2025-05-19 11:22:52.803 +02:00 [ERR] [AppUpdatesPage] App Add Failed: Omnissa Horizon Client
2025-05-19 12:07:27.512 +02:00 [ERR] Fetch.App
2025-05-19 12:07:27.512 +02:00 [ERR] Microsoft.UI.Xaml.UnhandledExceptionEventArgs

**Comment by tbwfdu** [comment]
@msconfig87 this seems very similar to the issues fixed in 0.8.1/0.8.2 but was (finally) resolved properly in 0.8.3.

Can you confirm which version you are trying this on?

**Comment by msconfig87** [comment]
Hi. Yes it's version 0.8.3.0

cheers
________________________________
Von: Pete Lindley ***@***.***>
Gesendet: Montag, 19. Mai 2025 23:35
An: tbwfdu/fetch ***@***.***>
Cc: msconfig87 ***@***.***>; Mention ***@***.***>
Betreff: Re: [tbwfdu/fetch] Upload to WS1 does not work - 400 (Bad Request) (Issue #16)

[https://avatars.githubusercontent.com/u/1597216?s=20&v=4]tbwfdu left a comment (tbwfdu/fetch#16)<https://github.com/tbwfdu/fetch/issues/16#issuecomment-2892312735>

@msconfig87<https://github.com/msconfig87> this seems very similar to the issues fixed in 0.8.1/0.8.2 but was (finally) resolved properly in 0.8.3.

Can you confirm which version you are trying this on?

**Comment by tbwfdu** [comment]
I think that this may be resolved now using the latest beta version.

**Comment by ishakHarichane220** [comment]
Am still facing the same issue on **0.9.5.0**, It seems related to the **organizationgroupid** value conversion  

<img width="820" height="170" alt="Image" src="https://github.com/user-attachments/assets/f9da5555-1c8b-4639-9892-6d13661ccae7" />






2025-12-09 08:15:34.761 -05:00 [INF] [SearchForApplicationsPage] Installer downloaded successfully: Sublime Text 3
2025-12-09 08:15:35.260 -05:00 [INF] [SearchForApplicationsPage] Starting Upload
2025-12-09 08:15:35.260 -05:00 [INF] [SearchForApplicationsPage] Uploading Detection Scripts
2025-12-09 08:15:35.324 -05:00 [ERR] Response status code does not indicate success: 400 (Bad Request).
2025-12-09 08:15:35.325 -05:00 [ERR] System.Net.Http
2025-12-09 08:15:35.660 -05:00 [ERR] Response status code does not indicate success: 400 (Bad Request).
2025-12-09 08:15:35.660 -05:00 [ERR] System.Net.Http
2025-12-09 08:15:35.660 -05:00 [INF] [SearchForApplicationsPage] Uploading Installation File
2025-12-09 08:15:35.661 -05:00 [INF] [FileUploadService] --> UploadFileToBlob
2025-12-09 08:15:43.238 -05:00 [ERR] [FileUploadService] Error uploading application. Status: 400 Bad Request. Body: {"errorCode":1020,"message":"Cannot convert organizationgroupid value:  to type System.Int32","activityId":"ee55bc10-d9ac-48f2-981c-f5c39fb077c2"}
2025-12-09 08:15:43.239 -05:00 [ERR] [FileUploadService] Could not parse 'Value' from response: 
2025-12-09 08:15:43.241 -05:00 [ERR] [SearchForApplicationsPage] Upload Process Cancelled: Sublime Text 3
